
CREATE DATABASE IF NOT EXISTS TrashDreams;


USE TrashDreams;


CREATE TABLE `basura` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `cantidad` DOUBLE NOT NULL,
  `tipo` VARCHAR(64) NOT NULL,
  `procedencia` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;